### ISSUE TITLE
Use size_t not ints

### ISSUE THREAD

**Issue by mbucc** [stephenmathieson/occurrences.c#1]
strlen returns size_t.  Why not use that instead of ints?

This code could behave badly on an Arduino (for example), where an int is two bytes and size_t is an unsigned int.

**Comment by mbucc** [comment]
http://stackoverflow.com/questions/25078285/replacing-32bit-loop-count-variable-with-64bit-introduces-crazy-performance-devi

Hmmmm.

**Comment by stephenmathieson** [comment]
hmm weird.  yeah, i'll update to use `size_t` in a bit
